### ISSUE TITLE
serial: fix THR Empty interrupt not being sent when stdout is full

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vm-superio#23]
If the `out` resource has a limited size (e.g. a named pipe), when it is at full capacity, a `write` request will result in blocking the driver indefinitely. This is caused by the THR empty interrupt no longer being sent, relevant lines [here](https://github.com/rust-vmm/vm-superio/blob/master/src/serial.rs#L381-L385).
This could be fixed, for example by always sending the THRE interrupt (even if the `write` failed).

**Comment by FedericoPonzi** [comment]
Can you please assign this to me? Thanks!
