### ISSUE TITLE
serial: implement TX FIFO

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vm-superio#25]
Our serial console implements only one FIFO (the RX one).

We need to implement the TX FIFO as well because otherwise it is hard to follow the specification. Not implementing this fifo has the following side effect - we are flooding the guest with interrupts. In non-FIFO mode, an interrupt will be generated when the THR gets empty (therefore, for each received byte). In FIFO mode the interrupt is sent when the TX FIFO gets completely empty (every FIFO_SIZE bytes).
A 16550 spec example [here](http://caro.su/msx/ocm_de1/16550.pdf). It is worth mentioning, the spec defines the FIFO_SIZE as 16 bytes for UART 16550(A). However, it can be for example 64 bytes as well, as it can be seen [here](https://elixir.bootlin.com/linux/v5.8.9/source/drivers/tty/serial/8250/8250_port.c#L179).

**Comment by FedericoPonzi** [comment]
Can I get this please?

**Comment by andreeaflorescu** [comment]
Closing this. For more details, please check the PR: https://github.com/rust-vmm/vm-superio/pull/28#issuecomment-799414268
