### ISSUE TITLE
Add metrics for serial console

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vm-superio#5]
Once we have a `metric` module in `vmm_sys_util` (https://github.com/rust-vmm/vmm-sys-util/pull/94), we can use it to add metrics for serial console.

**Comment by andreeaflorescu** [comment]
I think we can also decouple it from having that PR merged.

We could define the Serial metrics as a trait. If we do not provide a default implementation for it (other than for `()`), then we do not need to block this on the availability of the `Metric` in vmm-sys-utils.
